### ISSUE TITLE
Unable to use flood

### ISSUE THREAD

**Issue by Embraser01** [jfurrow/flood#129]
I followed the guide but there is a problem. As I see, it's because when we install, there isn't the folder 'server/assets' which is created by gulp. 

Also we can't launch gulp because the 'browser-sync' package is missing (devDependencies) : 

    Error: Cannot find module 'browser-sync'
        at Function.Module._resolveFilename (module.js:440:15)
        at Function.Module._load (module.js:388:25)
        at Module.require (module.js:468:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/var/www/flood/gulpfile.js:4:19)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)

Also the gulp task need 'envify' which is also a devDependencies.

    Version: webpack 1.13.2
    Time: 3639ms
                          Asset     Size  Chunks             Chunk Names
        ./server/assets//app.js  1.74 kB       0  [emitted]  main
    ./server/assets//app.js.map  1.44 kB       0  [emitted]  main

    ERROR in ./~/babel-polyfill/lib/index.js
    Module build failed: Error: Cannot resolve module 'envify' in /var/www/flood/node_modules/babel-polyfill/lib

Doing a 'npm install envify browser-sync' then a 'npm run preinstall' fix the problem ;)

**Comment by jfurrow** [comment]
Thanks, this is fixed in https://github.com/jfurrow/flood/pull/132
