### ISSUE TITLE
TypeError if rtorrent has no torrent at all

### ISSUE THREAD

**Issue by gretel** [jfurrow/flood#15]
```
GET /client/settings?property=sortTorrents 304 80.846 ms - -
TypeError: Cannot read property 'length' of undefined
    at Object.clientUtil.mapClientProps (/usr/home/tom/src/flood/server/util/clientUtil.js:227:16)
    at TorrentCollection.updateTorrents (/usr/home/tom/src/flood/server/models/TorrentCollection.js:75:34)
    at ClientRequest.request.postProcess [as postProcessFn] (/usr/home/tom/src/flood/server/models/client.js:95:26)
    at ClientRequest.handleSuccess (/usr/home/tom/src/flood/server/models/ClientRequest.js:78:23)
    at _fulfilled (/usr/home/tom/src/flood/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/home/tom/src/flood/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/home/tom/src/flood/node_modules/q/q.js:796:13)
    at /usr/home/tom/src/flood/node_modules/q/q.js:604:44
    at runSingle (/usr/home/tom/src/flood/node_modules/q/q.js:137:13)
    at flush (/usr/home/tom/src/flood/node_modules/q/q.js:125:13)
```
as soon as the amount of torrents is larger than zero it starts to load fine.

**Comment by jfurrow** [comment]
Thanks for reporting this! Fixed in #16

**Comment by gretel** [comment]
the issue has returned.

**Comment by jfurrow** [comment]
Sorry you're hitting this issue again. Unfortunately I can't reproduce it, could you provide more details?

1. Are you sure you have the latest `master` branch checked out?
2. Is rtorrent empty when you start it, or you removing torrents when you hit this error? I tried both and could not reproduce the error.
3. How are you removing these torrents? Through the Flood UI or some other method?
4. What version of rtorrent are you running?

Any other relevant details would be helpful.

For me, I'm the API returns `null` as expected and the UI is displaying the "No torrents to display" message:
![](http://cl.ly/382w1J44460h/Screen%20Shot%202016-06-27%20at%208.40.52%20PM.png)

**Comment by gretel** [comment]
@jfurrow i am sorry, while the symptom appeared to be similar it's a very different story:
`Connection refused at 127.0.0.1:5000. Check these values in config.js and ensure that rTorrent is running.`
that has been true - as soon as i did start *rtorrent* the UI came up nicely - did upgrade to latest master nonetheless :)
thanks a lot for taking care!
