### ISSUE TITLE
Errors 500 when I try to go to the interface

### ISSUE THREAD

**Issue by Spheerys** [jfurrow/flood#159]
Hi,

Flood is running good until I try to go to http://myIP:3000
On the screen, I have this kind of errors : 

```
GET /api/stats 500 25.839 ms - 59
Trace: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
    at ClientRequest.onCompleteFn (/srv/seedbox/flood/server/util/ajaxUtil.js:7:17)
    at ClientRequest.handleError (/srv/seedbox/flood/server/models/ClientRequest.js:69:12)
    at _rejected (/srv/seedbox/flood/node_modules/q/q.js:844:24)
    at /srv/seedbox/flood/node_modules/q/q.js:870:30
    at Promise.when (/srv/seedbox/flood/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/srv/seedbox/flood/node_modules/q/q.js:788:41)
    at /srv/seedbox/flood/node_modules/q/q.js:604:44
    at runSingle (/srv/seedbox/flood/node_modules/q/q.js:137:13)
    at flush (/srv/seedbox/flood/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
GET /api/client/torrents 500 20.340 ms - 59
GET /api/history?snapshot=fiveMin 304 27.249 ms - -
Trace: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
    at ClientRequest.onCompleteFn (/srv/seedbox/flood/server/util/ajaxUtil.js:7:17)
    at ClientRequest.handleError (/srv/seedbox/flood/server/models/ClientRequest.js:69:12)
    at _rejected (/srv/seedbox/flood/node_modules/q/q.js:844:24)
    at /srv/seedbox/flood/node_modules/q/q.js:870:30
    at Promise.when (/srv/seedbox/flood/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/srv/seedbox/flood/node_modules/q/q.js:788:41)
    at /srv/seedbox/flood/node_modules/q/q.js:604:44
    at runSingle (/srv/seedbox/flood/node_modules/q/q.js:137:13)
    at flush (/srv/seedbox/flood/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
GET /api/stats 500 26.362 ms - 59
Trace: { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
    at ClientRequest.onCompleteFn (/srv/seedbox/flood/server/util/ajaxUtil.js:7:17)
    at ClientRequest.handleError (/srv/seedbox/flood/server/models/ClientRequest.js:69:12)
    at _rejected (/srv/seedbox/flood/node_modules/q/q.js:844:24)
    at /srv/seedbox/flood/node_modules/q/q.js:870:30
    at Promise.when (/srv/seedbox/flood/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/srv/seedbox/flood/node_modules/q/q.js:788:41)
    at /srv/seedbox/flood/node_modules/q/q.js:604:44
    at runSingle (/srv/seedbox/flood/node_modules/q/q.js:137:13)
    at flush (/srv/seedbox/flood/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
```

What's going wrong ?

**Comment by jfurrow** [comment]
It looks to me like Flood can't communicate to rTorrent. Are you sure rTorrent is running and that it was compiled with XMLRPC support? Have you configured the `scgi` values in `config.js` under? Are you using a socket to communicate with rTorrent?

**Comment by jfurrow** [comment]
I'm going to close this because it seems to be resolved, but feel free to reopen if you're still having the problem.

**Comment by Spheerys** [comment]
OK it was the port inside the scgi values in config.js.
Thanks ;)
