### ISSUE TITLE
maxBuffer exceeded when getting mediainfo

### ISSUE THREAD

**Issue by jfurrow** [jfurrow/flood#187]
@maximuml reported in https://github.com/jfurrow/flood/issues/85:

error for single file

```
Trace: { error:
{ [Error: stdout maxBuffer exceeded]
cmd: 'mediainfo /home/rtorrent/downloads/hdd2/HDTV_PRO' } }
at /home/flood/server/util/ajaxUtil.js:7:17
at /home/flood/server/util/mediainfo.js:26:15
at ChildProcess.exithandler (child_process.js:220:5)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at maybeClose (internal/child_process.js:821:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
GET /api/mediainfo?hash=EFF762F8408D395F0D3080EA62A0DA908D9EA9DD 500 37637.223 ms - 75
```

**Comment by jfurrow** [comment]
@maximuml What happens when you try to run `mediainfo` via your terminal on this file?

**Comment by jfurrow** [comment]
@maximuml Fixed in https://github.com/jfurrow/flood/pull/188
