### ISSUE TITLE
Clean Ubuntu 16 install fails. 

### ISSUE THREAD

**Issue by haihosilver** [jfurrow/flood#27]
```
npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@3.7.0 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@3.7.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/asdf/flood/npm-debug.log

npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! flood@0.0.0 start: `npm prune && npm install && ./node_modules/.bin/gulp dist && nodemon ./server/bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@0.0.0 start script 'npm prune && npm install && ./node_modules/.bin/gulp dist && nodemon ./server/bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flood package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm prune && npm install && ./node_modules/.bin/gulp dist && nodemon ./server/bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flood
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls flood
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/asdf/flood/npm-debug.log

asdf@asdf:~/flood$ cat /home/asdf/flood/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle flood@0.0.0~prestart: flood@0.0.0
6 silly lifecycle flood@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle flood@0.0.0~start: flood@0.0.0
8 verbose lifecycle flood@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle flood@0.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/asdf/flood/node_modules/.bin:/home/asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sbin
10 verbose lifecycle flood@0.0.0~start: CWD: /home/asdf/flood
11 silly lifecycle flood@0.0.0~start: Args: [ '-c',
11 silly lifecycle   'npm prune && npm install && ./node_modules/.bin/gulp dist && nodemon ./server/bin/www' ]
12 silly lifecycle flood@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle flood@0.0.0~start: Failed to exec start script
14 verbose stack Error: flood@0.0.0 start: `npm prune && npm install && ./node_modules/.bin/gulp dist && nodemon ./server/bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid flood@0.0.0
16 verbose cwd /home/asdf/flood
17 error Linux 4.4.0-24-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error flood@0.0.0 start: `npm prune && npm install && ./node_modules/.bin/gulp dist && nodemon ./server/bin/www`
22 error Exit status 1
23 error Failed at the flood@0.0.0 start script 'npm prune && npm install && ./node_modules/.bin/gulp dist && nodemon ./server/bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the flood package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm prune && npm install && ./node_modules/.bin/gulp dist && nodemon ./server/bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs flood
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls flood
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jfurrow** [comment]
Thanks for posting this. It's failing at the `node-sass` installation, maybe just that specific version of `node-sass` has issues. Try running `npm install node-sass@latest` in your local checkout of this repo. If that succeeds then run `npm install && ./node_modules/.bin/gulp dist && nodemon ./server/bin/www`. If that fails then we'll need to figure something else out.

Thanks for the issue!

**Comment by KennyWuLee** [comment]
`apt-get install nodejs-legacy`

**Comment by jfurrow** [comment]
I tested this on a new Ubuntu 16.04 install and verified that it does work when you use `nodejs-legacy`. You can use the same `npm` package. More details here: http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu
