### ISSUE TITLE
Crash when downloading via UI

### ISSUE THREAD

**Issue by bengadbois** [jfurrow/flood#275]
On commit `ca3fbbaece833ac42d3ade1b9b5e8315be3fb5b7`. Downloading 900MB files.

stdout says
```
GET /api/client/torrents/taxonomy 304 12.301 ms - -
buffer.js:11
    super(arg1, arg2, arg3);
    ^

RangeError: Array buffer allocation failed
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at createUnsafeBuffer (buffer.js:38:12)
    at allocate (buffer.js:181:12)
    at Function.Buffer.allocUnsafe (buffer.js:141:10)
    at new Buffer (buffer.js:78:19)
    at ReadStream.<anonymous> (/home/x/flood/node_modules/archiver-utils/index.js:39:15)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)

npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/home/x/.nvm/versions/node/v6.9.5/bin/node" "/home/x/.nvm/versions/node/v6.9.5/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! flood@0.0.0 start: `node server/bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flood@0.0.0 start script 'node server/bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flood package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flood
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls flood
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/x/flood/npm-debug.log
```

npm-debug.log says
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/x/.nvm/versions/node/v6.9.5/bin/node',
1 verbose cli   '/home/x/.nvm/versions/node/v6.9.5/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle flood@0.0.0~prestart: flood@0.0.0
6 silly lifecycle flood@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle flood@0.0.0~start: flood@0.0.0
8 verbose lifecycle flood@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle flood@0.0.0~start: PATH: /home/x/.nvm/versions/node/v6.9.5/lib/node_modules/npm/bin/node-gyp-bin:/home/x/flood/node_modules/.bin:/home/x/.nvm/versions/node/v6.9.5/bin:/home/x/bin:/home/x/.local/bin:/home/x/bin:/home/x/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
10 verbose lifecycle flood@0.0.0~start: CWD: /home/x/flood
11 silly lifecycle flood@0.0.0~start: Args: [ '-c', 'node server/bin/www' ]
12 silly lifecycle flood@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle flood@0.0.0~start: Failed to exec start script
14 verbose stack Error: flood@0.0.0 start: `node server/bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/x/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/x/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid flood@0.0.0
16 verbose cwd /home/x/flood
17 error Linux 3.14.32-xxxx-grs-ipv6-64
18 error argv "/home/x/.nvm/versions/node/v6.9.5/bin/node" "/home/x/.nvm/versions/node/v6.9.5/bin/npm" "start"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error flood@0.0.0 start: `node server/bin/www`
22 error Exit status 1
23 error Failed at the flood@0.0.0 start script 'node server/bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the flood package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server/bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs flood
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls flood
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jfurrow** [comment]
Thanks for filing the issue, I'll look into this.

**Comment by jfurrow** [comment]
@bengadbois Is your server short on memory? It seems that's what causes the issue. I'm able to download 4gb+ files without problems.

**Comment by bengadbois** [comment]
Yeah looks like flood/node eating up the ram, and flood consequently dies.

I can reproduce consistently

1) Startup flood normally and flood idling at 1GB (of 8GB server)
2) Go UI and find a torrent with 10x 1GB files
3) Select all of them and hit download, flood now at 3GB
4) Wait a while, doesn't seem to start downloading (flood CPU jumped up and then back down to idle amount)
5) Refresh the page, flood now idling 3GB
Keep repeating steps 2-5 and flood ends up holding onto more and more memory, eventually crashing

The key to reproducing seems to be using multiple large files

**Comment by jfurrow** [comment]
You're right, I was able to reproduce this. I'll work on a solution, thanks!

**Comment by liquidox** [comment]
Somewhat worrisome that this is still open, any progress?

**Comment by jfurrow** [comment]
@liquidox To me this isn't really a priority, so I haven't touched it.

To anyone who wants to implement a solution, I think the best course for this is not archiving files in Node at all, and instead relying on some external archiving binary. This means Flood needs to provide a method for users to select in the UI which archiving binary they'd like to use. That same UI should support selecting external binaries for other things, too (like mediainfo, mktorrent, etc).

**Comment by dcousens** [comment]
Is this still an issue?

**Comment by dcousens** [comment]
See #474 for a fix :), streams the archive directly, no tmp files
