### ISSUE TITLE
Can't launch Flood after update

### ISSUE THREAD

**Issue by Spheerys** [jfurrow/flood#283]
Hi,

i have followed the instructions to upgrade Flood and I have an error during the "npm start" : 
```
% npm start

> flood@0.0.0 start /srv/seedbox/flood
> node server/bin/www

/srv/seedbox/flood/server/models/client.js:181
  findFilesByIndicies(indices, fileTree = {}) {
                                        ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/srv/seedbox/flood/server/routes/api.js:8:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Linux 4.8.3-std-1
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.8.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! flood@0.0.0 start: `node server/bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@0.0.0 start script 'node server/bin/www'.
npm ERR! This is most likely a problem with the flood package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flood
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls flood
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/seedbox/flood/npm-debug.log

```

What's going wrong ?

**Comment by jfurrow** [comment]
You need to update your version of node.

**Comment by Spheerys** [comment]
OK thank you for the information !
It was not so obvious
