### ISSUE TITLE
Get stuck after first screen after logon

### ISSUE THREAD

**Issue by v0vc** [jfurrow/flood#291]
Hi man! 
Just did step-by-step by instruction, and after logon screen had this picture 
![image](https://cloud.githubusercontent.com/assets/9407549/23974668/d9b3434c-09f5-11e7-8e9b-99ee7fb16724.png)

Console says:
GET /api/client/torrents 304 3.310 ms - -
GET /api/client/torrents/taxonomy 304 5.177 ms - -
GET /api/notifications?limit=10&start=0 304 8.049 ms - -
GET /api/history?snapshot=fiveMin 304 12.382 ms - -
GET /api/stats 500 13.383 ms - 85

Probably, any case of user rights? Looks like api/stats 500 - is not good...I don't know, please help, thanks!

**Comment by wopian** [comment]
Refreshing the page will sometimes work when that happens

**Comment by v0vc** [comment]
Refreshing doesn't help me

**Comment by jfurrow** [comment]
It's worrisome that all of you are experiencing this. What versions of Node are you all running?

**Comment by wopian** [comment]
7.7.3

**Comment by manusauvage** [comment]
@v0vc are you accessing flood through a reverse proxy, by any chance? If so, may I suggest you check the baseURI value in your config?

**Comment by jfurrow** [comment]
@v0vc Please run Flood as follows: `NODE_ENV=development npm start`, then paste the output from the node server. It should give a stack trace for the 500 error.

**Comment by wopian** [comment]
Ah the one it occasionally hung on for me was Auth Status, with all requests OK, and goes away with a refresh.

![](http://i.imgur.com/WnCRIIY.png)

**Comment by v0vc** [comment]
#jfurrow# stacktrace output:

Trace: { Error: connect ENOENT /srv/lock/=rtorrent.sock
    at Object.exports._errnoException (util.js:1033:11)
    at exports._exceptionWithHostPort (util.js:1056:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/srv/lock/=rtorrent.sock' }
    at ClientRequest.onCompleteFn (/srv/flood/server/util/ajaxUtil.js:8:19)
    at ClientRequest.handleError (/srv/flood/server/models/ClientRequest.js:77:12)
    at _rejected (/srv/flood/node_modules/q/q.js:844:24)
    at /srv/flood/node_modules/q/q.js:870:30
    at Promise.when (/srv/flood/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/srv/flood/node_modules/q/q.js:788:41)
    at /srv/flood/node_modules/q/q.js:604:44
    at runSingle (/srv/flood/node_modules/q/q.js:137:13)
    at flush (/srv/flood/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)

**Comment by v0vc** [comment]
Resolved by changing socket: true to false and using correct scgi adress, thanks
