### ISSUE TITLE
Can no longer filter by tracker?

### ISSUE THREAD

**Issue by NoLooseEnds** [jfurrow/flood#381]
I pulled the latest source, and I can no longer sort by tracker. It still only shows all torrents. 
I tried to get rid off all, and start over, but still the same issue.

Also, If I add i.e "Created" to the torrent list, it still does not show up in the "Sort by" dropdown menu.

Anyone else experienced this?

Attached screenshot. Notice that a tracker with 1 torrent is selected, but it still shows all.
<img width="1429" alt="flood" src="https://user-images.githubusercontent.com/4103531/27044531-c540c106-4f95-11e7-8d49-43ce1131c7a8.png">

**Comment by jfurrow** [comment]
I'll check this out, thanks for reporting!

**Comment by darkbeuh** [comment]
Same here.

Fresh install. Filters worked a couple times than nothing.

I believe this happened after I tried combining column sorting and filters

**Comment by Daiyousei** [comment]
Same error for me.

I get an exception in the dev console : 
```
app.js:19 Uncaught TypeError: Cannot read property 'includes' of undefined
    at https://flood.MyDomain/app.js:19:303
    at Array.filter (native)
    at r (https://flood.MyDomain/app.js:19:267)
    at t.value (https://flood.MyDomain/app.js:18:24429)
    at t.value (https://flood.MyDomain/app.js:18:28658)
    at Object.ID_5 (https://flood.MyDomain/app.js:18:30303)
    at t.e._invokeCallback (https://flood.MyDomain/app.js:17:10445)
    at t.e.dispatch (https://flood.MyDomain/app.js:17:10247)
    at t.value (https://flood.MyDomain/app.js:17:9158)
    at Object.setTorrentTrackerFilter (https://flood.MyDomain/app.js:19:17529)
```

**Comment by noraj1337** [comment]
In the Concentrated view filter by tracker doesn't work neither.

**Comment by 320x200** [comment]
Same here, just updated today.

`TypeError: e.trackers is undefined`

**Comment by jfurrow** [comment]
Finally fixed, sorry everyone for the delay & the really dumb bug.
