### ISSUE TITLE
Error: Cannot find module 'pug'

### ISSUE THREAD

**Issue by mikkoc** [jfurrow/flood#388]
Hello,
I'm getting this error when trying to reach my flood Docker container:

```
Error: Cannot find module 'pug'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at new View (/usr/src/app/node_modules/express/lib/view.js:80:30)
    at Function.render (/usr/src/app/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:971:7)
    at app.use (/usr/src/app/server/app.js:52:9)
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:315:13)
```

docker logs:
```
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.8.0
npm info lifecycle flood@1.0.0~prestart: flood@1.0.0
npm info lifecycle flood@1.0.0~start: flood@1.0.0

> flood@1.0.0 start /usr/src/app
> node server/bin/www
```

What am I missing?

**Comment by jfurrow** [comment]
It seems like you need to run `npm install`. `pug` is a hard dependency for Flood, so all you need to do is install all dependencies with `npm install`.
