### ISSUE TITLE
[Windows] Torrents are not visible in the list

### ISSUE THREAD

**Issue by vBm** [jfurrow/flood#43]
I've tried `Flood` on Windows and it works just fine until i add torrent. I get torrent running in `rTorrent` in background and it's downloading but `Flood` doesn't show anything, upon refreshing `Flood` i get stuck into infinite loading. After removal of torrent from `rTorrent` i get `Flood` showing it's initial screen again.
Error that i saw in console is this one. Hope it helps.

```
Trace: TypeError: Cannot read property 'length' of undefined
    at ClientRequest.request.postProcess [as postProcessFn] (E:\toolz\repository\flood\server\models\client.js:148:30)
    at ClientRequest.handleSuccess (E:\toolz\repository\flood\server\models\ClientRequest.js:79:23)
    at _fulfilled (E:\toolz\repository\flood\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (E:\toolz\repository\flood\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (E:\toolz\repository\flood\node_modules\q\q.js:796:13)
    at E:\toolz\repository\flood\node_modules\q\q.js:604:44
    at runSingle (E:\toolz\repository\flood\node_modules\q\q.js:137:13)
    at flush (E:\toolz\repository\flood\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ClientRequest.onCompleteFn (E:\toolz\repository\flood\server\util\ajaxUtil.js:7:17)
    at ClientRequest.handleError (E:\toolz\repository\flood\server\models\ClientRequest.js:69:12)
    at _rejected (E:\toolz\repository\flood\node_modules\q\q.js:844:24)
    at E:\toolz\repository\flood\node_modules\q\q.js:870:30
    at Promise.when (E:\toolz\repository\flood\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (E:\toolz\repository\flood\node_modules\q\q.js:788:41)
    at E:\toolz\repository\flood\node_modules\q\q.js:604:44
    at runSingle (E:\toolz\repository\flood\node_modules\q\q.js:137:13)
    at flush (E:\toolz\repository\flood\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jfurrow** [comment]
Sorry, I haven't had a chance to look into this yet, but will do so on a VM as soon as possible.

**Comment by jfurrow** [comment]
@vBm Are you still seeing this issue? Sorry, it's actually not trivial to install rTorrent on Windows so I gave up on this a while ago.

**Comment by vBm** [comment]
@jfurrow It's just too much hustle to set it up properly. Just compiled it from scratch and silly rT doesn't even work unfortunately. God knows what's broken in cygwin :D

**Comment by vBm** [comment]
Just finished compiling fresh rTorrent via cygwin and flood is working correctly !

There's a small annoyance regarding SSL CA cert but I guess I didn't properly compile it.

Ticket can be closed as well. 👍

**Comment by jfurrow** [comment]
Thanks @vBm!
