### ISSUE TITLE
Latest changes breaks Flood on my system (Ubuntu 17.04)

### ISSUE THREAD

**Issue by NoLooseEnds** [jfurrow/flood#485]
I tried a clean install also, but get this error on the build and run.

```
[rt:~/flood]$ npm run build                                                                                                                                     (master✱)

> flood@1.0.0 build /home/rt/flood
> node client/scripts/build.js

/home/rt/flood/client/scripts/build.js:54
    ({ stats, previousFileSizes, warnings }) => {
     ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! flood@1.0.0 build: `node client/scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flood@1.0.0 build script 'node client/scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flood package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node client/scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flood
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls flood
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rt/flood/npm-debug.log
[rt:~/flood]$ npm start                                                                                                                                         (master✱)

> flood@1.0.0 start /home/rt/flood
> node server/bin/start.js

/home/rt/flood/server/bin/start.js:5
const {startWebServer} = require('./web-server');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! flood@1.0.0 start: `node server/bin/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flood@1.0.0 start script 'node server/bin/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flood package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/bin/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flood
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls flood
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rt/flood/npm-debug.log
```

*/home/rt/flood/npm-debug.log*
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.7.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle flood@1.0.0~prestart: flood@1.0.0
6 silly lifecycle flood@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle flood@1.0.0~start: flood@1.0.0
8 verbose lifecycle flood@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle flood@1.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/rt/flood/node_modules/.bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/home/rt/bin
10 verbose lifecycle flood@1.0.0~start: CWD: /home/rt/flood
11 silly lifecycle flood@1.0.0~start: Args: [ '-c', 'node server/bin/start.js' ]
12 silly lifecycle flood@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle flood@1.0.0~start: Failed to exec start script
14 verbose stack Error: flood@1.0.0 start: `node server/bin/start.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:854:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
15 verbose pkgid flood@1.0.0
16 verbose cwd /home/rt/flood
17 error Linux 4.10.0-35-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.7.2
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error flood@1.0.0 start: `node server/bin/start.js`
22 error Exit status 1
23 error Failed at the flood@1.0.0 start script 'node server/bin/start.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the flood package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server/bin/start.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs flood
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls flood
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by randomnonsense** [comment]
In the home dir remove all npm and related folders (.npm, .config and .node-gyp), and "node_modules" from "flood/" and do a clean "npm install". See if that helps.

**Comment by NoLooseEnds** [comment]
I've done a "clean install", did not help. Same error.

**Comment by randomnonsense** [comment]
Yes, but aren't you running very old node and npm? Upgrade to 0.8.5 or the most recent one for you.

**Comment by NoLooseEnds** [comment]
Could be, I'm running the default installed on that Ubuntu version. I'll look into it.

**Comment by NoLooseEnds** [comment]
@randomnonsense You were right, upgrading node did the trick. Currently on v. 8.7.0, and it went fine. 

Thank you!
