### ISSUE TITLE
error when starting flood in arch linux

### ISSUE THREAD

**Issue by anastiel** [jfurrow/flood#618]
my config in .rtorrent

```
# SCGI port, used to communicate with Flood
scgi_port = 127.0.0.1:5000
```

I did not change anything in the flood configuration

```
[anastiel@manjaro flood]$ sudo npm start
[sudo] password for anastiel: 

> flood@1.0.0 start /srv/flood
> node server/bin/start.js

Failed to start web server:
Static assets (index.html) are missing. Please check the 'Compiling assets and starting the server' section of README.md.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 start: `node server/bin/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-01T09_41_14_157Z-debug.log



[anastiel@manjaro flood]$ sudo npm start

> flood@1.0.0 start /srv/flood
> node server/bin/start.js

Failed to start web server:
Static assets (index.html) are missing. Please check the 'Compiling assets and starting the server' section of README.md.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 start: `node server/bin/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-01T09_42_36_635Z-debug.log

[anastiel@manjaro flood]$ sudo systemctl --failed
0 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
[anastiel@manjaro flood]$ sudo npm update nod-sass
[anastiel@manjaro flood]$ sudo npm run build

> flood@1.0.0 build /srv/flood
> node client/scripts/build.js

module.js:557
    throw err;
    ^

Error: Cannot find module 'webpack-manifest-plugin'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/flood/client/config/webpack.config.prod.js:8:24)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/flood/client/scripts/build.js:21:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 build: `node client/scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-01T09_48_04_811Z-debug.log


LOG

  GNU nano 2.9.2                                  2018-02-01T09_40_34_013Z-debug.log                                            

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle flood@1.0.0~prestart: flood@1.0.0
6 info lifecycle flood@1.0.0~start: flood@1.0.0
7 verbose lifecycle flood@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle flood@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/srv/flood/node_$
9 verbose lifecycle flood@1.0.0~start: CWD: /srv/flood
10 silly lifecycle flood@1.0.0~start: Args: [ '-c', 'node server/bin/start.js' ]
11 silly lifecycle flood@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle flood@1.0.0~start: Failed to exec start script
13 verbose stack Error: flood@1.0.0 start: `node server/bin/start.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid flood@1.0.0
15 verbose cwd /srv/flood
16 verbose Linux 4.9.78-1-MANJARO
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error flood@1.0.0 start: `node server/bin/start.js`
22 error Exit status 1
23 error Failed at the flood@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Have solution?

**Comment by d0tfile** [comment]
Did you run commands `npm install` and `npm run build`?

**Comment by anastiel** [comment]
yes Yes, I did it and it's not going to happen

**Comment by anastiel** [comment]
[anastiel@manjaro ~]$ cd /srv/flood/
[anastiel@manjaro flood]$ ls
CHANGELOG.md  client  config.docker.js  config.js  config.template.js  Dockerfile  flood.png  LICENSE  node_modules  package.json  package-lock.json  README.md  server  shared
[anastiel@manjaro flood]$ sudo npm install

> nodemon@1.14.3 postinstall /srv/flood/node_modules/nodemon
> node -e "console.log('\u001b[32mLove nodemon? You can now support the project via the open collective:\u001b[22m\u001b[39m\n > \u001b[96m\u001b[1mhttps://opencollective.com/nodemon/donate\u001b[0m\n')"

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 351 packages in 227.395s
[anastiel@manjaro flood]$

**Comment by anastiel** [comment]
is error?

**Comment by d0tfile** [comment]
No, it is normal output of `npm install`. What about `npm run build`? Do you see output like on screen?
![image](https://user-images.githubusercontent.com/4760202/35673460-b37a3a22-0752-11e8-94de-26c99d48c1c3.png)

**Comment by anastiel** [comment]
[img]https://ptpimg.me/8drrjo.png[/img]

**Comment by anastiel** [comment]
[anastiel@manjaro flood]$ sudo npm run build
[sudo] password for anastiel: 

> flood@1.0.0 build /srv/flood
> node client/scripts/build.js

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  398.21 KB  assets/static/js/main.49b15bb1.js
  16.23 KB   assets/static/css/main.cb94aa40.css

**Comment by d0tfile** [comment]
Check now output of `sudo npm start`.

**Comment by anastiel** [comment]
ooooh running
https://ptpimg.me/115570.png

**Comment by anastiel** [comment]
but it did not come with the file that was already in rtorrent

**Comment by anastiel** [comment]
strange that it's not downloading

**Comment by anastiel** [comment]
https://ptpimg.me/56682j.png
https://ptpimg.me/8p5nwr.png
https://ptpimg.me/3u95e9.png
https://ptpimg.me/5igrmi.png

**Comment by anastiel** [comment]
have solution An error occurred while running mediainfo on the server. Check that mediainfo is installed and available in the PATH to Flood.?

**Comment by d0tfile** [comment]
Just install mediainfo package (via pacman, if you use Arch Linux).

**Comment by anastiel** [comment]
but i have mediainfo o-o
 sudo cp /bin/mediainfo /usr/sbin/
[sudo] password for anastiel: 
cp: '/bin/mediainfo' and '/usr/sbin/mediainfo' are the same file

**Comment by noraj1337** [comment]
@anastiel 

> Failed to start web server:
> Static assets (index.html) are missing. Please check the 'Compiling assets and starting the server' section of README.md.

This was because you didn't run `npm run build` as in the README.


When you had permission denied it was because you wanted to write in a protected folder without proper permissions.

And now your `mediainfo` problem is certainly not a flood issue but a miss-configuration. 

There is no flood issue so I am closing.

Please keep in mind that The project is accepting issues (bugs report), feature or enhancement requests, discussions and questions but **not personal support**.
