### ISSUE TITLE
Cant install in ubuntu 18.04

### ISSUE THREAD

**Issue by hallonfras** [jfurrow/flood#719]
I cant install in ubuntu 18.04. Running sudo npm install gives me these errors

kiwikaffe@kladdkaka:/srv/torrent/flood$ sudo npm install

> geoip-country-only@1.1.8 postinstall /srv/torrent/flood/node_modules/geoip-country-only
> npm run-script updatedb

> geoip-country-only@1.1.8 updatedb /srv/torrent/flood/node_modules/geoip-country-only
> node scripts/updatedb.js

Fetching  https://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/srv/torrent/flood/node_modules/geoip-country-only/tmp'
    at Object.fs.mkdirSync (fs.js:885:18)
    at mkdir (/srv/torrent/flood/node_modules/geoip-country-only/scripts/updatedb.js:43:6)
    at fetch (/srv/torrent/flood/node_modules/geoip-country-only/scripts/updatedb.js:131:2)
    at /srv/torrent/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:1149:20
    at /srv/torrent/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:375:13
    at iterate (/srv/torrent/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/srv/torrent/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:281:9)
    at Object.async.inject.async.foldl.async.reduce (/srv/torrent/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:374:15)
    at /srv/torrent/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:1148:19
    at /srv/torrent/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:166:37
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geoip-country-only@1.1.8 updatedb: `node scripts/updatedb.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geoip-country-only@1.1.8 updatedb script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kiwikaffe/.npm/_logs/2018-09-26T13_42_50_301Z-debug.log
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN flood@1.0.0 No repository field.
npm WARN flood@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geoip-country-only@1.1.8 postinstall: `npm run-script updatedb`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geoip-country-only@1.1.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kiwikaffe/.npm/_logs/2018-09-26T13_42_51_691Z-debug.log
kiwikaffe@kladdkaka:/srv/torrent/flood$ npm run-script updatedb
npm ERR! missing script: updatedb

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kiwikaffe/.npm/_logs/2018-09-26T13_43_20_789Z-debug.log

Thanks in advance for the help!

## Your Environment

* Version used:
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version:Ubuntu 18.04 lts

**Comment by hallonfras** [comment]
Allright tell me if i've missed something.

**Comment by noraj** [comment]
@hallonfras 

> Not sure how do i check?

Run those commands where you installed flood.

  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`

Also please fill *Steps to reproduce* you didn't just run `sudo npm install`. You must have done something before. Did you followed flood pre-requisites of flood and node-gyp ?

Also some notes that were removed from the README:

> * Note: Since #523 [node-gyp](https://www.npmjs.com/package/node-gyp) is needed. **IF** you need `sudo`, use `sudo npm i --unsafe-perm` (see [here](https://github.com/nodejs/node-gyp/issues/454) for why `--unsafe-perm`) else installation will fail. If you dont need sudo just use `npm i` as usual.
>  * If your system use python3 as default you will need to install python2 and use `npm i --python="/usr/bin/python2"`.

But it is preferred to install flood somewhere where you user has permissions or to chown/chmod the directory in order to. Doing an `npm install` with `sudo` is not a good thing and will be way more complex to manage.

**Comment by noraj** [comment]
@hallonfras Any update ?

**Comment by wireless-r** [comment]
Hi. I experience the exact same error. Instead of opening a new issue I post info below:

Version: v1.0.0

Commit ID: a7a849e7bf6f80857d727d31f1ef9200998bc54f

Node version 10.14.2, also tried with version 8 and 11

Operating system: Linux raspberrypi 4.14.79-v7+

**Comment by GottZ** [comment]
did you try https://github.com/creationix/nvm yet?

**Comment by noraj** [comment]
Actually it is better to use https://github.com/nodenv/nodenv

**Comment by GottZ** [comment]
oh that's interesting. so far i always deploy with nvm and .nvmrc but this is looking more user friendly.

**Comment by noraj** [comment]
@GottZ nodenv is a node adaption from rbenv, there is a comparation between rbenv and rvm (like nvm and nodenv), see here https://github.com/rbenv/rbenv/wiki/Why-rbenv%3F. I was using rvm and nvm before but it was always ending in such a mess, complex config and errors.
