### ISSUE TITLE
Make a new github release, the current release is quite old.

### ISSUE THREAD

**Issue by robertbaker** [jfurrow/flood#734]
---
name: "💡 Feature Request"
about: "Suggest an idea for this project"
---
Type: Feature Request

- [x ] If you want to contribute to the project please review the [contributing guidelines](https://github.com/jfurrow/flood/blob/master/.github/CONTRIBUTING.md).

## Summary
The current github release is outdated, some custom dockerfiles are pulling from github releases.

## Idea of implementation
Make a new release

**Comment by noraj** [comment]
@jfurrow I agree there is only v1.0.0 since long time.

**Comment by robertbaker** [comment]
@noraj btw, the issue template settings need a review. github now allows users to select a template, but it seems like that's broken.

**Comment by bbashy** [comment]
Can't really do releases until you get some versioning system down. Right now we can't even get things merged and into master, let alone release and changelog as well.

@robertbaker We're waiting on that to be merged in #723

**Comment by dhanjit** [comment]
```
> geoip-country-only@1.1.8 updatedb /home/dhanjit/resources/flood/node_modules/geoip-country-only
> node scripts/updatedb.js

fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/home/dhanjit/resources/flood/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/dhanjit/resources/flood/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/dhanjit/resources/flood/node_modules/fstream/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geoip-country-only@1.1.8 updatedb: `node scripts/updatedb.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geoip-country-only@1.1.8 updatedb script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

I am facing this issue.

**Comment by phoenixlzx** [comment]
@dhanjit try downgrade your nodejs and npm version. I used LTS version 10.13.0 and npm 6.4.1 get no errors.

**Comment by noraj** [comment]
Yeah remove the 1.0.0 release and provide a new one.
